// System v6.0.0
using System;
// System.ComponentModel.DataAnnotations v6.0.0
using System.ComponentModel.DataAnnotations;
// System.ComponentModel.DataAnnotations.Schema v6.0.0
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Core.Entities
{
    /// <summary>
    /// Represents a contract between a customer and the organization.
    /// Manages contract details and customer relationship with proper validation.
    /// </summary>
    [Table("Contracts")]
    public class Contract
    {
        /// <summary>
        /// Primary key identifier for the contract.
        /// Auto-generated by the database.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        /// <summary>
        /// Name of the contract.
        /// Required field with maximum length of 100 characters.
        /// </summary>
        [Required(ErrorMessage = "Contract name is required")]
        [StringLength(100, ErrorMessage = "Contract name cannot exceed 100 characters")]
        public string Name { get; set; }

        /// <summary>
        /// Indicates whether the contract is currently active.
        /// </summary>
        [Required]
        public bool Active { get; set; }

        /// <summary>
        /// UTC timestamp when the contract was created.
        /// </summary>
        [Required]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Username or identifier of the user who created the contract.
        /// </summary>
        [Required(ErrorMessage = "Created by information is required")]
        [StringLength(50, ErrorMessage = "Created by identifier cannot exceed 50 characters")]
        public string CreatedBy { get; set; }

        /// <summary>
        /// Foreign key reference to the associated Customer.
        /// </summary>
        [Required(ErrorMessage = "Customer ID is required")]
        [ForeignKey("Customer")]
        public int CustomerId { get; set; }

        /// <summary>
        /// Navigation property for the associated Customer entity.
        /// Enables lazy loading of the related Customer data.
        /// </summary>
        public virtual Customer Customer { get; set; }

        /// <summary>
        /// Initializes a new instance of the Contract class with default values.
        /// Sets Active status to true and CreatedAt to current UTC time.
        /// </summary>
        public Contract()
        {
            Active = true;
            CreatedAt = DateTime.UtcNow;
        }
    }
}