apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: production
type: Opaque
stringData:
  # Database Connection String with enhanced security parameters
  ConnectionStrings__DefaultConnection: "Server=sql-server;Database=InspectorDB;User Id=inspector_app;Password=<password>;TrustServerCertificate=True;MultipleActiveResultSets=True;Min Pool Size=5;Max Pool Size=100;Connect Timeout=30;Connection Lifetime=300;Retry Logic=true;Max Retries=3;Encrypt=True"
  
  # JWT Authentication Settings
  JwtSettings__SecretKey: "<jwt-secret-key-min-32-chars>"
  
  # Email Service Configuration
  EmailSettings__Username: "notifications@inspectorapp.com"
  EmailSettings__Password: "<email-password>"
  EmailSettings__RetryCount: "3"
  EmailSettings__TimeoutSeconds: "30"
  
  # OneDrive Integration Settings
  OneDriveSettings__ClientId: "<onedrive-client-id>"
  OneDriveSettings__ClientSecret: "<onedrive-client-secret>"
  OneDriveSettings__TenantId: "<azure-tenant-id>"
  OneDriveSettings__Scopes: "Files.ReadWrite.All Sites.ReadWrite.All User.Read"
  
  # Azure Storage Configuration
  AzureStorage__ConnectionString: "DefaultEndpointsProtocol=https;AccountName=<storage-account>;AccountKey=<storage-key>;EndpointSuffix=core.windows.net"
  AzureStorage__SasToken: "<sas-token>"

---
apiVersion: v1
kind: Secret
metadata:
  name: web-secrets
  namespace: production
type: Opaque
stringData:
  # Frontend Authentication
  VUE_APP_AUTH_KEY: "<frontend-auth-key>"
  
  # Frontend OneDrive Integration
  VUE_APP_ONEDRIVE_CLIENT_ID: "<onedrive-client-id>"
  VUE_APP_ONEDRIVE_SCOPES: "Files.ReadWrite.All Sites.ReadWrite.All User.Read"
  
  # CORS Configuration
  VUE_APP_CORS_ALLOWED_ORIGINS: "https://app.inspectorapp.com,https://admin.inspectorapp.com"